name: Deploy API Docs to Github Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install maturin mkdocs mkdocs-autorefs mkdocstrings mkdocstrings-python ruff
      - run: maturin build
      - run: pip install target/wheels/*.whl
      - run: mkdocs gh-deploy --force --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}